### ISSUE TITLE
when left idle, the site showsno slots available

### ISSUE THREAD

**Issue by Emon69420** [aishwaryalonarkar/aishwaryalonarkar.github.io-cowin#1]
![image](https://user-images.githubusercontent.com/63973473/119099257-5b6f0400-ba34-11eb-8f47-89d5ca4723a6.png)
![image](https://user-images.githubusercontent.com/63973473/119099494-95d8a100-ba34-11eb-982c-426e4a5acba4.png)

hope you check in this, or i can add a re submit banner as the slots are shown again when re submitted

**Comment by aishwaryalonarkar** [comment]
Hey Emon, thanks for the feedback. The site is goes down while the slots are being uploaded on the server site. And it will resume as soon as it finds available slots.
